### ISSUE TITLE
Use separator options

### ISSUE THREAD

**Issue by aboungnaseng857** [andrewboni/countup-angularjs-directive#2]
Hello,

I try to use separator option as countUp.js exemple :

https://inorganik.github.io/countUp.js/

I have added this following code at line 15 of countup-angularjs-directive.js :

`
if (attrs.separator != null) {
 opts.separator = attrs.separator;
}
`

My html :

`    	<h1 count-up id="blah" num-decimals="1" separator="," ng-model="page1.specialfruit.count">0</h1>`

but it's not working, separator option stay a '.' character,  Help !

**Comment by aboungnaseng857** [comment]
:+1:

**Comment by andrewboni** [comment]
Hi, were you able to get this to work?

**Comment by aboungnaseng857** [comment]
Hello,

It's okay, I use 'decimal' attribute inside options args, It work as well.

Thanks @andrewboni  !

:+1:

**Comment by moreaup** [comment]
Hi,

I'm trying to do the same but I don't see how using decimal is gonna help.

Do you know how to replace the comma by nothing ?

Thanks in advance :)
